### ISSUE TITLE
error while ask the list of available sets of files

### ISSUE THREAD

**Issue by cyphermaster** [druidops/beholder#6]
can get the values  :
~~~
root@leonardo:~/beholder/rainbow# ./rainbow.py -f cf3/policy_server
Querying_redis_server 127.0.0.1
fatboy (23:36/2015-01-07T13:09) 192.168.1.1
### Keys found: 1 ###
~~~

but asking for the list will fail 
~~~~
root@leonardo:~/beholder/rainbow# ./rainbow.py -a
Querying_redis_server 127.0.0.1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./rainbow.py", line 83, in redis_query
    hostname, key = item.split('#')
ValueError: need more than 1 value to unpack


~~~~

**Comment by cyphermaster** [comment]
Be advised this only happen when only 1 key is stored.

**Comment by lpefferkorn** [comment]
@cyphermaster please check on leonardo :)
